name: mark_shop
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-63.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  rive: ^0.10.1
  fluttertoast: ^8.1.3
  blurry_modal_progress_hud: ^1.1.0
  provider: ^6.0.5
  flutter_gif: ^0.0.4
  cloud_firestore: ^4.4.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/image1.png
    - lib/assets/gi.gif
    
  fonts:
    - family: Anaqa
      fonts:
        - asset: lib/assets/Anaqa-Semibold.ttf
